export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_REBOTS_PENDING'
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_REBOTS_SUCCESS'
export const REQUEST_ROBOTS_FAILED = 'REQUEST_REBOTS_FAILED'